### ISSUE TITLE
feat: mechanism for retry of failed tests

### ISSUE THREAD

**Issue by puneeth072003** [puneeth072003/CODESOURCERER#37]
Implement a robust mechanism to automatically retry the generation of test cases for failed scenarios. This feature aims to enhance the reliability and efficiency of the test generation process by identifying failures and re-attempting their generation with improved prompts or configurations.

### TODO
- [ ] Failure Detection
- [ ] new AI model trained for retries specifically
- [ ] limit niumber of retries to 3

**Comment by soorya-u** [comment]
## This Issue has been blocked and must need following things to be completed:

- [ ] Completion of App Workflow (to raise a PR with the generated test files to the branch)
- [ ] Requires a Workflow which basically runs the Generated tests
